#!/bin/sh

# keep grub UI from coming up
sudo apt-mark hold grub

# make sure os is up to date
sudo apt-get update
sudo apt-get -y upgrade

# Install required packages
sudo apt-get install -y git g++ make openssl libssl-dev
sudo apt-get install -y libprotobuf-dev protobuf-compiler
sudo apt-get install -y python-tk python-dev python-setuptools python-crypto python-requests
sudo apt-get install -y swig
sudo apt-get install -y python-argparse
sudo apt-get install -y python-pygame

# tools
sudo apt-get install -y vim tmux ack-grep curl socat netcat wget stunnel

# get XIA source & build
cd /
sudo git clone https://github.com/XIA-Project/xia-core.git
sudo chmod -R 777 xia-core
cd xia-core
git checkout develop

# Delete xsockconf.ini files that are not for GENI XIA-prototype
#find . -name "xsockconf*.ini" -exec rm -rf {} \;

./configure
make
