#!/bin/sh
# assume the rest of the node is uptodate and just build xia

cd /tmp
git clone https://github.com/XIA-Project/xia-core.git
cd xia-core
git checkout xia-v2
DEBUG=1 ./configure
make
cd ..
mv xia-core ~
