#!/bin/sh
# assume the rest of the node is uptodate and just build xia

cd
git clone https://github.com/XIA-Project/xia-core.git
#sudo chmod -R 777 xia-core
cd xia-core
git checkout xia-v2
DEBUG=1 ./configure
make
