#!/bin/sh
#
# Slaspdash script for creating an XIA tutorial network on GENI.
# This code was written on osx, and will require changes to the following 2  shortcuts to work on linux.
#
rtl="/Applications/omniTools-2.6/readyToLogin.app/Contents/MacOS/readyToLogin"
omni="/Applications/omniTools-2.6/omni.app/Contents/MacOS/omni --error "

if [ $# != 2 ]; then
	echo usage: xbuild slivername aggregate
	echo use: omni nicknames to find valid aggregate names
	exit
fi

T="$(date +%s)"

echo creating slice
$omni createslice $1
[ $? -ne 0 ] && exit

echo creating sliver
$omni createsliver -a $2 $1 xiatutorial.rspec
[ $? -ne 0 ] && exit

echo waiting for sliver to be ready
numready=0
while true; do
	numready=`$rtl -a $2 $1 | grep status:ready | wc | tr -s " " | cut -d " " -f 2`
	if [ $numready -eq 5 ]; then
		break
	elif [ $numready -gt 0 ]; then
		echo "$numready node(s) are in the ready state"
	else
		echo rechecking...
	fi
	sleep 15
done

T="$(($(date +%s)-T))"

$rtl -a $2 $1 -o

read -p "Backup and replace ~/.ssh/config? (yn)" x
if [ "$x" == "y" ]; then
	if [ -e ~/.ssh/config.save ]; then
		read -p "~/.ssh/config.save already exists. Overwrite? " x
		if [ "$x" == "y" ]; then
			cp ~/.ssh/config ~/.ssh/config.save
		fi
	fi
	cp sshconfig.txt ~/.ssh/config
else
	echo "the new ssh config settings can be found in sshconfig.txt"

printf "Imaging %s on %s took %02d:%02d\n" $1 $2 "$((T/60))" "$((T%60))"

